baseurl: https://blog.pwed.me/
title: Pwed's Blog
theme: ghostwriter
languageCode: en-us
copyright: Frederick Stoddart
disqusShortname: blog-pwed-me
pygmentsUseClasses: true
pygmentsCodefences: true
uglyurls: true
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false
author:
  name: Fred Stoddart
  profile: /page/about.html
taxonomies:
  tag: tags
params:
  mainSections:
    - post
  intro: true
  headline: Pwed's Blog
  description: |
    A place where I blog about the cool AWS tools I play with
  github: https://github.com/pwed
  gitlab: https://gitlab.com/pwed
  linkedin: https://linkedin.com/in/frederickstoddart/
  twitter: https://twitter.com/genuinepwed
  email: freddiestoddart000@gmail.com
  api: api.pwed.me
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: false
  shareLinkedIn: true
  dateFormat: Mon, Jan 2, 2006
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  plausibleAnalytics:
    domain: ""
    serverURL: ""
permalinks:
  post: /:year/:month/:day/:filename/
menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project.html
    - name: About
      url: /page/about.html
      weight: 4
